sudo: required

language: ruby

services:
 - docker

env:
  - DOCKER_TAG="matthewpatterson/mattpatt.io:${TRAVIS_COMMIT:0:7}"

before_script:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
  - echo "Building docker tag $DOCKER_TAG"

script: make build push
