user: deploy
group: deploy
pid: /var/run/thatmattpattis.at/thin.pid
timeout: 30
wait: 30
log: /var/log/thatmattpattis.at/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
no-epoll: true
daemonize: true
socket: /var/run/thatmattpattis.at/thin.sock
chdir: /home/deploy/thatmattpattis.at/current
